### ISSUE TITLE
有没有办法去掉i3最下面的状态栏

### ISSUE THREAD

**Issue by alex-techs** [tzuhsiao/baidunetdisk-docker#1]
我尝试了注释掉了 i3status，实时状态消失了，但是还有空间占用，以及最左侧的一个数字
```nginx
bar {
        # status_command i3status
}
```

![image](https://user-images.githubusercontent.com/20666153/94090070-4b703780-fe47-11ea-8ef5-6915aa3e2bee.png)

**Comment by tzuhsiao** [comment]
可以的， https://i3wm.org/docs/userguide.html#_display_mode

```
bar {
	mode hide
	hidden_state hide
}
```

**Comment by tzuhsiao** [comment]
https://github.com/tzuhsiao/baidunetdisk-docker/commit/381e1aa54cbfcaac9ebb5bba48f3fa261fe8dc16

**Comment by alex-techs** [comment]
非常感谢
