### ISSUE TITLE
小白求教，有没有试过在群晖的系统下可以用吗，我试了但是连接VNC后黑屏，网页打开是一个列表，用里面的vnc.html链接进去也是黑屏，如下图

### ISSUE THREAD

**Issue by xiaominglei001** [tzuhsiao/baidunetdisk-docker#2]
VNC进去黑屏
https://gitee.com/xiaominglei001/forMarkdown/blob/master/%E6%8D%95%E8%8E%B78.PNG

网页打开是一个列表，用里面的vnc.html链接进去登陆后也是黑屏
https://gitee.com/xiaominglei001/forMarkdown/blob/master/%E6%8D%95%E8%8E%B79.PNG

**Comment by tzuhsiao** [comment]
我自己就是用的群晖，没遇到过这种问题呢，有log么？ 或者看看你群晖里docker的设置

**Comment by xiaominglei001** [comment]
> 我自己就是用的群晖，没遇到过这种问题呢，有log么？ 或者看看你群晖里docker的设置

解决了，不过当时这里没回复，用的另一个映像解决的，应该和这里的问题差不多（https://github.com/gshang2017/docker/issues/43），可能是我系统版本或文件夹权限配置的问题。
